---
name: Add issues and prs to GitHub Projects
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "*/10 * * * *"
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - id: token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          # permissions: >-
          #   {"projects": "write"}
          # repositories: >-
          #   []
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.31.0
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: orgov -v
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: orgov add-to-project
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - uses: suzuki-shunsuke/notify-workflow-error-action@e5e8817e62eb122231d162dbc8309c4d05a21b2e # v0.1.0
        if: always()
        with:
          issue_number: "1"
          status: ${{ job.status }}
